name: s2_lamp1

####network#####
network: stage2
database_name: custom/lamp/1600
shader_config:
  sphere_direction: false
  human_light: false
apply_occ_loss: true
apply_std_loss: false
occ_loss_step: 20000
is_nerf: false

######loss######
loss: ['eikonal','std','nerf_render']
val_metric: ['stage2']
key_metric_name: psnr
eikonal_weight: 0.05
freeze_inv_s_step: 15000

####dataset#####
train_dataset_type: dummy
dataset_dir: anon
train_dataset_cfg:
  database_name: custom/lamp/1600
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: custom/lamp/1600

####trainier####
optimizer_type: adam
lr_type: warm_up_cos
lr_cfg: {}
total_step: 1200000
val_interval: 5000
save_interval: 1000
train_log_step: 20

downsample_ratio: 1.0