name: pen1

####network#####
network: shape
database_name: custom/eikonal_pen/1024
shader_config:
  sphere_direction: true
  human_light: false
apply_occ_loss: true
occ_loss_step: 20000

######loss######
loss: ['nerf_render','eikonal','std','init_sdf_reg','occ','outer_reg']
val_metric: ['shape_render']
key_metric_name: psnr
eikonal_weight: 0.1
freeze_inv_s_step: 15000

####dataset#####
train_dataset_type: dummy
dataset_dir: anon
train_dataset_cfg:
  database_name: custom/eikonal_pen/1024
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: custom/eikonal_pen/1024

####trainier####
optimizer_type: adam
lr_type: warm_up_cos
lr_cfg: {}
total_step: 300000
val_interval: 5000
save_interval: 1000
train_log_step: 20

