name: refrac_s2_sphere

####network#####
network: stage2
database_name: nerf/sphere_pot4
apply_acc_loss: true
occ_loss_step: 20000
is_nerf: true

######loss######
loss: ['eikonal','std','nerf_render']
val_metric: ['stage2']
key_metric_name: psnr
eikonal_weight: 0.1
freeze_inv_s_step: 10000

####dataset#####
train_dataset_type: dummy
dataset_dir: anon
train_dataset_cfg:
  database_name: nerf/sphere_pot4
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: nerf/sphere_pot4

####trainier####
optimizer_type: adam
lr_type: warm_up_cos
lr_cfg: {}
total_step: 1200000
val_interval: 5000
save_interval: 1000
train_log_step: 20

downsample_ratio: 1.0