name: kirsh_2

####network#####
network: stage2
database_name: nerf/thickbottle_kirsch_final
apply_acc_loss: true
shader_config:
  sphere_direction: false
  human_light: false
occ_loss_step: 20000
is_nerf: true
get_mask: true

######loss######
loss: ['eikonal','std','nerf_render']
val_metric: ['stage2']
key_metric_name: psnr
eikonal_weight: 0.02
freeze_inv_s_step: 5000

####dataset#####
train_dataset_type: dummy
dataset_dir: /home/sunjiamu/instant-ngp
train_dataset_cfg:
  database_name: nerf/thickbottle_kirsch_final
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: nerf/thickbottle_kirsch_final

####trainier####
optimizer_type: adam
lr_type: warm_up_cos
lr_cfg: {}
total_step: 1200000
val_interval: 5000
save_interval: 1000
train_log_step: 20

downsample_ratio: 1.0