name: orig_pig

####network#####
network: shape
database_name: nerf/pig_final
apply_acc_loss: true
occ_loss_step: 20000
is_nerf: true

######loss######
loss: ['nerf_render','eikonal','std','init_sdf_reg','occ','mask']
val_metric: ['shape_render']
key_metric_name: psnr
eikonal_weight: 0.01
freeze_inv_s_step: 60000

####dataset#####
train_dataset_type: dummy
dataset_dir: anon
train_dataset_cfg:
  database_name: nerf/pig_final
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: nerf/pig_final

####trainier####
optimizer_type: adam
lr_type: warm_up_cos
lr_cfg: {}
total_step: 300000
val_interval: 5000
save_interval: 1000
train_log_step: 20

