name: ball_0_7_0_68

####network#####
network: shape
database_name: nerf/ball_0_7_0_68
apply_acc_loss: true
occ_loss_step: 20000
is_nerf: true

######loss######
loss: ['nerf_render','eikonal','std','init_sdf_reg','occ','mask','outer_reg']
val_metric: ['shape_render']
key_metric_name: psnr
eikonal_weight: 0.2
freeze_inv_s_step: 15000

####dataset#####
train_dataset_type: dummy
dataset_dir: /home/sunjiamu/instant-ngp
train_dataset_cfg:
  database_name: nerf/ball_0_7_0_68
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: nerf/ball_0_7_0_68
####trainier####
optimizer_type: adam
lr_type: warm_up_cos
lr_cfg: {}
total_step: 500000
val_interval: 5000
save_interval: 1000
train_log_step: 20

